name: Build Dev image for Filecoin Green API

on:
  push:
    branches: [main]

# For configuration please see https://github.com/cristi-mb/build-be

env:
  SLACK_CHANNEL: infra-ci-filgreen
  AWS_REGION: us-east-1
  ECR_REPOSITORY: filecoin/filecoin-green-api
  NODE_VERSION: 23.x
  TAG_PREFIX: dev-

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set timestamp
        id: set-timestamp
        run: |
          echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
    
      - uses: cristi-mb/build-be@main
        id: build-be
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          ecr-repository: ${{ env.ECR_REPOSITORY }}
          docker-path: ${{ env.DOCKER_PATH }}
          node-version: ${{ env.NODE_VERSION }}
          tag-prefix: ${{ env.TAG_PREFIX }}
          tag-suffix: "-${{ steps.set-timestamp.outputs.timestamp }}"

      - name: Show image tag
        if: steps.build-be.outcome == 'success'
        run: echo "${{ steps.build-be.outputs.image-tag }}"
